import { type File } from "../../types/File";
export const FILES: File[] = [
    // ISO
    {
        title: "T01_iso_teoria_0",
        subjectId: "iso",
        course: "primero",
        unit: "tema1",
        ext: "pdf",
        resume: "Conceptos básicos de Sistemas Operativos",
    },
    {
        title: "T01_iso_presentacion_0",
        subjectId: "iso",
        course: "primero",
        unit: "tema1",
        ext: "pdf",
        resume: "Presentación de Conceptos básicos de Sistemas Operativos",
    },
    {
        title: "T02_iso_comandos_0",
        subjectId: "iso",
        course: "primero",
        unit: "tema2",
        ext: "pdf",
        resume: "Resumen de comandos básicos de Linux",
    },
    {
        title: "T02_iso_comandos_ejercicios_0",
        subjectId: "iso",
        course: "primero",
        unit: "tema2",
        ext: "pdf",
        resume: "Ejercicios de comandos básicos de Linux",
    },
    {
        title: "T02_iso_comandos_ejercicios_1",
        subjectId: "iso",
        course: "primero",
        unit: "tema2",
        ext: "pdf",
        resume: "Ejercicios de comandos básicos de Linux",
    },
    {
        title: "T02_iso_comandos_ejercicios_2",
        subjectId: "iso",
        course: "primero",
        unit: "tema2",
        ext: "pdf",
        resume: "Ejercicios de comandos básicos de Linux",
    },
    {
        title: "T02_iso_comandos_ejercicios_3",
        subjectId: "iso",
        course: "primero",
        unit: "tema2",
        ext: "pdf",
        resume: "Ejercicios de comandos básicos de Linux",
    },
    {
        title: "T02_iso_comandos_ejercicios_4",
        subjectId: "iso",
        course: "primero",
        unit: "tema2",
        ext: "pdf",
        resume: "Ejercicios de comandos básicos de Linux",
    },
    {
        title: "T02_iso_comandos_ejercicios_5",
        subjectId: "iso",
        course: "primero",
        unit: "tema2",
        ext: "pdf",
        resume: "Ejercicios de comandos básicos de Linux",
    },
    {
        title: "T02_iso_comandos_ejercicios_6",
        subjectId: "iso",
        course: "primero",
        unit: "tema2",
        ext: "pdf",
        resume: "Ejercicios de comandos básicos de Linux",
    },
    {
        title: "T02_iso_comandos_examen_0",
        subjectId: "iso",
        course: "primero",
        unit: "tema2",
        ext: "pdf",
        resume: "Examen de comandos básicos de Linux",
    },
    {
        title: "T03_iso_comandos_0",
        subjectId: "iso",
        course: "primero",
        unit: "tema3",
        ext: "pdf",
        resume: "Resumen de comandos de usuarios de Linux",
    },
    {
        title: "T03_iso_comandos_1",
        subjectId: "iso",
        course: "primero",
        unit: "tema3",
        ext: "pdf",
        resume: "Resumen de comandos de ficheros de Linux",
    },
    {
        title: "T03_iso_comandos_ejercicios_0",
        subjectId: "iso",
        course: "primero",
        unit: "tema3",
        ext: "pdf",
        resume: "Ejercicios de comandos de usuarios de Linux",
    },
    {
        title: "T03_iso_comandos_ejercicios_1",
        subjectId: "iso",
        course: "primero",
        unit: "tema3",
        ext: "pdf",
        resume: "Ejercicios de comandos de ficheros de Linux",
    },
    {
        title: "T03_iso_comandos_ejercicios_3",
        subjectId: "iso",
        course: "primero",
        unit: "tema3",
        ext: "pdf",
        resume: "Ejercicios de comandos de ficheros de Linux",
    },
    {
        title: "T03_iso_comandos_ejercicios_4",
        subjectId: "iso",
        course: "primero",
        unit: "tema3",
        ext: "pdf",
        resume: "Ejercicios de comandos de ficheros de Linux",
    },
    {
        title: "T03_iso_comandos_ejercicios_5",
        subjectId: "iso",
        course: "primero",
        unit: "tema3",
        ext: "pdf",
        resume: "Ejercicios de comandos de ficheros de Linux",
    },
    {
        title: "T03_iso_comandos_ejercicios_6",
        subjectId: "iso",
        course: "primero",
        unit: "tema3",
        ext: "pdf",
        resume: "Ejercicios de comandos de ficheros de Linux",
    },
    {
        title: "T03_iso_comandos_ejercicios_7",
        subjectId: "iso",
        course: "primero",
        unit: "tema3",
        ext: "pdf",
        resume: "Ejercicios de comandos de ficheros de Linux",
    },
    {
        title: "T03_iso_comandos_ejercicios_8",
        subjectId: "iso",
        course: "primero",
        unit: "tema3",
        ext: "pdf",
        resume: "Ejercicios de comandos de ficheros de Linux",
    },
    {
        title: "T03_iso_comandos_ejercicios_9",
        subjectId: "iso",
        course: "primero",
        unit: "tema3",
        ext: "pdf",
        resume: "Ejercicios de comandos de ficheros de Linux",
    },

    // BD
    {
        title: "T01_bases_teoria_0",
        subjectId: "bd",
        course: "primero",
        unit: "tema1",
        ext: "pdf",
        resume: "Introducción a las bases de datos",
    },
    {
        title: "T02_bases_ejercicios_0",
        subjectId: "bd",
        course: "primero",
        unit: "tema2",
        ext: "pdf",
        resume: "Ejercicios de diagrama Entidad Relación",
    },
    {
        title: "T02_bases_ejercicios_1",
        subjectId: "bd",
        course: "primero",
        unit: "tema2",
        ext: "pdf",
        resume: "Ejercicios de diagrama Entidad Relación",
    },
]